
get http://localhost:3000/todos/?status=TO%20DO
###

get http://localhost:3000/todos/:todoId/
###

post http://localhost:3000/todos/
###
 

put http://localhost:3000/todos/:todoId/
###


delete http://localhost:3000/todos/:todoId/
